### ISSUE TITLE
pod 'VoxboneSDK' does not work

### ISSUE THREAD

**Issue by squalx** [voxbone-workshop/ios-sdk#2]
90% of the time my `pod install` fails because 'VoxboneSDK' is not reachable. It seems that Cocoapods caches this so once it gets it on one Mac it's fine. But when someone needs a fresh install or we change the version, it generally fails.

    [!] Unable to find a specification for `VoxboneSDK`

I'm not sure why you guys have hidden your repo, or if I need special github permissions to access it. Please advice.

Thanks.

**Comment by fikrifirat** [comment]
@squalx The repo is public, as the CocoaPod. Can you share your podfile contents and complete logs from terminal so we can understand what's happening?
